services:
  hive-server:
    image: bde2020/hive:3.1.2-postgresql-metastore
    container_name: hive-server
    depends_on:
      - hive-metastore
    environment:
      HIVE_METASTORE_URI: thrift://hive-metastore:9083
      HIVE_METASTORE_DB_TYPE: mysql
      MYSQL_HOST: host.docker.internal  # 指向宿主机 MySQL
      MYSQL_PORT: 3306
      MYSQL_DATABASE: metastore       # 你本机 MySQL 已建的 Metastore DB
      MYSQL_USER: hiveuser
      MYSQL_PASSWORD: 123456
    ports:
      - "10000:10000"
      - "10002:10002"
    command: /opt/hive/bin/hiveserver2

  hive-metastore:
    image: bde2020/hive-metastore:3.1.2
    container_name: hive-metastore
    environment:
      HIVE_METASTORE_DB_TYPE: mysql
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    ports:
      - "9083:9083"
    command: /opt/hive/bin/hive --service metastore
