spring:
  profiles:
    active: local
  application:
    name :data-warehouse-query-service

# MyBatis Plus 通用配置
mybatis-plus:
  mapper-locations: classpath:/xml/**/*.xml
  configuration:
    map-underscore-to-camel-case: true